### PR TITLE
Canned message - Extend messages length

### PR DESCRIPTION
**Pull request by prampec**
See description of PR https://github.com/meshtastic/Meshtastic-device/pull/1232

Note that protos changes are not part of this commit!

Most of this code changes are made by @mkinney .

### CODE REVIEW

**Comment by prampec** [comment]
Also note, that unit tests are not updated/executed by me.

**Comment by mkinney** [comment]
I just "approved" the work flow.

Can you fix the lint warnings? I think you just need to add "self.Response = None" in the constructor for the most of those warnings. The other warning can be "worked around" by modifying the .pylintrc file "max-module-lines=1200" to something like 1400.

**Comment by mkinney** [comment]
Also, do you know what commit of the protobufs?

**Comment by mkinney** [comment]
Well, I'm just going to merge this then do a PR to fix the warnings.

**Comment by prampec** [comment]
I do not know too much about python, and I don't know how to execute these checks locally (pylnt, pytest, coverage, etc.). Please give me more details on the topic!

**Pull request merged**
