### PR TITLE
revamp the serial connection to avoid Tbeam reboots

### PR DESCRIPTION
**Pull request by mkinney**
Got this to pass the smoke1 on a Tbeam with firmware 1.2.50.41dcfdd from mac using usb

### CODE REVIEW

**Comment by mkinney** [comment]
Same TBeam from passes smoke1 on ubuntu
Heltec21 on same firmware passes smoke1 on mac

**Comment by mkinney** [comment]
smoke1 almost passed. had an issue with test1_smoke_nodes() -- unrelated to this change
unit test failed on trying to remove output.txt in test_main_info_with_seriallog_output_txt().

**Comment by mkinney** [comment]
smoke1 works on mac/HeltecV2
smoke1 works on windows/TBeam
smoke1 works on ubuntu/TBeam
smoke1 works on mac/TBeam

**Comment by mkinney** [comment]
Fix #139

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-python-1-2-48/4614/1

**Pull request merged**
