### PR TITLE
Remotely administering your node #105 #312

### PR DESCRIPTION
**Pull request by KiwiHC16**
As explained in:

https://github.com/meshtastic/Meshtastic-python/issues/105

The remote control "randomly" works.

Here is the code to avoid the crash and make the system work.

### CODE REVIEW

**Comment by mkinney** [comment]
Do you want help fixing these lint warnings?

```
************* Module meshtastic.mesh_interface
meshtastic/mesh_interface.py:1[7](https://github.com/meshtastic/Meshtastic-python/runs/5759577115?check_suite_focus=true#step:7:7)1:0: C0303: Trailing whitespace (trailing-whitespace)
meshtastic/mesh_interface.py:172:4: C0116: Missing function or method docstring (missing-function-docstring)
************* Module meshtastic.node
meshtastic/node.py:264:0: C0303: Trailing whitespace (trailing-whitespace)
meshtastic/node.py:2[9](https://github.com/meshtastic/Meshtastic-python/runs/5759577115?check_suite_focus=true#step:7:9)0:0: C0303: Trailing whitespace (trailing-whitespace)
meshtastic/node.py:499:0: C0303: Trailing whitespace (trailing-whitespace)
meshtastic/node.py:500:11: C0121: Comparison 'errorFound == True' should be 'errorFound is True' if checking for the singleton value True, or 'errorFound' if testing for truthiness (singleton-comparison)
meshtastic/node.py:491:4: R17[10](https://github.com/meshtastic/Meshtastic-python/runs/5759577115?check_suite_focus=true#step:7:10): Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
```

**Comment by KiwiHC16** [comment]
Hi @mkinney,

I see some error messages about  "Trailing whitespace" and I need to do some cleanup. I use VSCode, is there any recommendation about the configuration of it.

I need help for "Missing function or method docstring". I don't know what I have to do here.

"errorFound" I'll do the modification.

"Either all return statements in a function should return an expression" I'l check this point.

**Comment by KiwiHC16** [comment]
I injected correction for issues found by pylint. I hope it's ok now.

**Comment by KiwiHC16** [comment]
I see erreur in the test but not on the area I modified. Could you have a look ? What should I do ?

**Comment by KiwiHC16** [comment]
It is creating regression for example:
```
meshtastic --port /dev/ttyUSB0 --dest \!f266e0f0 --get position_broadcast_secs
Connected to radio
Requesting preferences from remote node.
Be sure:
 1. There is a SECONDARY channel named 'admin'.
 2. The '--seturl' was used to configure.
 3. All devices have the same modem config. (i.e., '--ch-longfast')
 4. All devices have been rebooted after all of the above. (optional, but recommended)
Note: This could take a while (it requests remote channel configs, then writes config)
Requesting channel 0 info from remote node (this could take a while)
Requesting channel 1 info from remote node (this could take a while)
Requesting channel 2 info from remote node (this could take a while)
position_broadcast_secs: 0
Completed getting preferences
```
use to work and now I get:
```
meshtastic --port /dev/ttyUSB0 --dest \!f266e0f0 --get position_broadcast_secs
Connected to radio
Aborting due to: 'NoneType' object has no attribute 'preferences'
```

SO I'm cancelling this Merge Request.

**Pull request closed without merging**
