### PR TITLE
Expose API over http server

### PR DESCRIPTION
**Pull request by luandro**
This is very naive implementation (first time trying Python) of how we could expose the API over an http server, in order for radios to communicate over USB with a computer in order to use the web ui.

Ideally we'd have exactly the same endpoints as the web-server that has already been implemented.

### CODE REVIEW

**Comment by geeksville** [comment]
hmm - see my comment in web chat.  I'm not sure of the usecase of the python API in tern exposing stuff over http.? The device code is already doing that.  Given that do you think there is an extra need for the python code to offer this feature?

**Comment by luandro** [comment]
The device does that through WiFi. The use case I'm thinking of is for doing that same without WiFi, over USB. But probably could be achived via TCP?

**Comment by geeksville** [comment]
but if someone is connecting to the device locally via USB (either android or python), can't they just use the android or python APIs? (which are easier)

**Comment by luandro** [comment]
But how would I use the Python api on a web application?

**Comment by geeksville** [comment]
For a web application, wouldn't you be better off just using meshtastic-js (which can talk directly to the device the same way the python code does)?

**Comment by luandro** [comment]
Meshtastic-js only supports Bluetooth or the http endpoints created by the device using WiFi. When we don't want to use WiFi, and communicate using a usb connection there's currently no way to communicate with the board.

I'm proposing for the python-api to mimic the device generated http api.

Makes sense?

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-to-connect-remote-villages-deep-in-the-amazon/2643/14

**Comment by sachaw** [comment]
@luandro I plan to implement webSerial support very soon, which should cover your use case

**Comment by luandro** [comment]
@sachaw I think my usecase might be a bit different, as I won't be acessing the Meshtastic API from the browser of the computer where the LoRa radio is connected to, I'll consuming the API from other devices in the same LAN. Does that make sense?

The easiest path forward for me would be to create a NodeJS API wrapping and exposing the Python API.

**Comment by sachaw** [comment]
By "I'll be consuming the API from other devices in the same LAN", can you elaborate on this because I don't see any situations where this couldn't be achieved how you want it to

**Comment by sachaw** [comment]
What I'm thinking you want to make would be something along the lines of:

Meshtastic device <-> (Node serial <-> exposes arbitrary/proxied JSON API endpoints) <-> some networked client

So basically you have a worker/daemon machine that has a physical connection to a node

**Comment by luandro** [comment]
> Meshtastic device <-> (Node serial <-> exposes arbitrary/proxied JSON API endpoints) <-> some networked client

@sachaw that's exactly what I need. Could Meshtastic.js serial provide for this use case? I thought it was meant only for the browser, but it can also run on NodeJS?

**Comment by sachaw** [comment]
It will, once I add node serial support, which will be soon

**Comment by luandro** [comment]
Ok, that sounds like a plan. Closing this in favor of Meshtastic.js NodeJS serial. Thanks @sachaw and @geeksville for the attention.

**Pull request closed without merging**
