### PR TITLE
sort possible options/tests, figured out how to mock so --info can be…

### PR DESCRIPTION
**Pull request by mkinney**
… tested

### CODE REVIEW

**Comment by mkinney** [comment]
Weird. It works on my machine...

**Comment by mkinney** [comment]
oh. darn it. I had a device connected during testing

**Comment by mkinney** [comment]
int, smoke1, and smokewifi all pass

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-python-1-2-46/4501/1

**Pull request merged**
